# Generated by Django 3.1.7 on 2021-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pve', '0002_auto_20210302_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='Bouwsoort',
            field=models.ManyToManyField(blank=True, null=True, to='pve.Bouwsoort'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='Doelgroep',
            field=models.ManyToManyField(blank=True, null=True, to='pve.Doelgroep'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='TypeObject',
            field=models.ManyToManyField(blank=True, null=True, to='pve.TypeObject'),
        ),
    ]
