export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// CRUD Items
export const GET_PVEITEMS = 'GET_PVEITEMS';
export const PVEITEMS_LOADING = 'PVEITEMS_LOADING';
export const DELETE_PVEITEM = 'DELETE_PVEITEM';
export const ADD_PVEITEM = 'ADD_PVEITEM';
export const ADD_PVEITEM_LOADING = 'ADD_PVEITEM_LOADING';
export const ADD_PVEITEM_LOADED = 'ADD_PVEITEM_LOADED';
export const GET_ERRORS = 'GET_ERRORS';

// CRUD HOOFDSTUKKEN
export const GET_HOOFDSTUKKEN = 'GET_HOOFDSTUKKEN';
export const HOOFDSTUKKEN_LOADING = 'HOOFDSTUKKEN_LOADING';
export const DELETE_HOOFDSTUK = 'DELETE_HOOFDSTUK';
export const ADD_HOOFDSTUK = 'ADD_HOOFDSTUK';
export const ADD_HOOFDSTUK_LOADING = 'ADD_HOOFDSTUK_LOADING';
export const ADD_HOOFDSTUK_LOADED = 'ADD_HOOFDSTUK_LOADED';

// CRUD PARAGRAVEN
export const GET_PARAGRAVEN = 'GET_PARAGRAVEN';
export const PARAGRAVEN_LOADING = 'PARAGRAVEN_LOADING';
export const DELETE_PARAGRAAF = 'DELETE_PARAGRAAF';
export const ADD_PARAGRAAF = 'ADD_PARAGRAAF';
export const ADD_PARAGRAAF_LOADING = 'ADD_PARAGRAAF_LOADING';
export const ADD_PARAGRAAF_LOADED = 'ADD_PARAGRAAF_LOADED';

