export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// CRUD Leads
export const GET_PVEITEMS = 'GET_PVEITEMS';
export const PVEITEMS_LOADING = 'PVEITEMS_LOADING';
export const DELETE_PVEITEM = 'DELETE_PVEITEM';
export const ADD_PVEITEM = 'ADD_PVEITEM';
export const ADD_PVEITEM_LOADING = 'ADD_PVEITEM_LOADING';
export const ADD_PVEITEM_LOADED = 'ADD_PVEITEM_LOADED';
export const GET_ERRORS = 'GET_ERRORS';