# Generated by Django 3.1.7 on 2021-03-02 01:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrstatus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.FloatField(default=None, max_length=100)),
                ('naam', models.CharField(default=None, max_length=500)),
                ('plaats', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('plaatsnamen', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('vhe', models.FloatField(default=None, max_length=100)),
                ('pensioenfonds', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('datum_aangemaakt', models.DateTimeField(auto_now_add=True)),
                ('datum_recent_verandering', models.DateTimeField(auto_now=True, verbose_name='recente_verandering')),
                ('pveconnected', models.BooleanField(blank=True, default=False, null=True)),
                ('frozenLevel', models.IntegerField(default=0, null=True)),
                ('fullyFrozen', models.BooleanField(default=False)),
                ('Smarthome', models.BooleanField(default=False)),
                ('AED', models.BooleanField(default=False)),
                ('EntreeUpgrade', models.BooleanField(default=False)),
                ('Pakketdient', models.BooleanField(default=False)),
                ('JamesConcept', models.BooleanField(default=False)),
                ('belegger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.belegger')),
            ],
        ),
    ]
