# Generated by Django 3.1.7 on 2021-03-02 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pve', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bouwsoort1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pve.bouwsoort'),
        ),
        migrations.AddField(
            model_name='project',
            name='bouwsoort2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbouwsoort_project', to='pve.bouwsoort'),
        ),
        migrations.AddField(
            model_name='project',
            name='bouwsoort3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubbouwsoort_project', to='pve.bouwsoort'),
        ),
        migrations.AddField(
            model_name='project',
            name='doelgroep1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pve.doelgroep'),
        ),
        migrations.AddField(
            model_name='project',
            name='doelgroep2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdoelgroep_project', to='pve.doelgroep'),
        ),
        migrations.AddField(
            model_name='project',
            name='doelgroep3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubdoelgroep_project', to='pve.doelgroep'),
        ),
        migrations.AddField(
            model_name='project',
            name='organisaties',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='organisatie_projecten', to='accounts.Organisatie'),
        ),
        migrations.AddField(
            model_name='project',
            name='permitted',
            field=models.ManyToManyField(default=None, related_name='permitted_projecten', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='statuscontract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.contractstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeObject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pve.typeobject'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeObject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtypeobject_project', to='pve.typeobject'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeObject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubtypeobject_project', to='pve.typeobject'),
        ),
    ]
